2020-10-11 19:47:07,535 ERROR: Exception on /auth/login [GET] [in c:\final project\final-course-project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Final project\Final-course-project\app\auth\routes.py", line 27, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Final project\Final-course-project\app\templates\auth\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Final project\Final-course-project\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\final project\final-course-project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\final project\final-course-project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\final project\final-course-project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\final project\final-course-project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Final project\Final-course-project\app\templates\base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\final project\final-course-project\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2020-10-11 20:07:26,095 INFO: Microblog startup [in C:\Final project\Final-course-project\app\__init__.py:72]
2020-10-11 20:07:29,160 ERROR: Exception on /auth/login [GET] [in c:\final project\final-course-project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Final project\Final-course-project\app\auth\routes.py", line 27, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Final project\Final-course-project\app\templates\auth\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Final project\Final-course-project\app\templates\base.html", line 26, in template
    <li><a href="{{ url_for('auth.login') }}">{{ 'Login' ) }}</a></li>
jinja2.exceptions.TemplateSyntaxError: unexpected ')'
2020-10-11 20:08:26,111 INFO: Microblog startup [in C:\Final project\Final-course-project\app\__init__.py:72]
2020-10-11 20:08:45,650 ERROR: Exception on /auth/login [GET] [in c:\final project\final-course-project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Final project\Final-course-project\app\auth\routes.py", line 27, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Final project\Final-course-project\app\templates\auth\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Final project\Final-course-project\app\templates\base.html", line 26, in template
    <li><a href="{{ url_for('auth.login') }}">{{ 'Login' ) }}</a></li>
jinja2.exceptions.TemplateSyntaxError: unexpected ')'
2020-10-11 20:14:19,914 INFO: Microblog startup [in C:\Final project\Final-course-project\app\__init__.py:72]
2020-10-11 20:23:58,022 INFO: Microblog startup [in C:\Final project\Final-course-project\app\__init__.py:72]
2020-10-11 20:34:41,139 INFO: Microblog startup [in C:\Final project\Final-course-project\app\__init__.py:72]
2020-10-11 20:55:19,061 INFO: Microblog startup [in C:\Final project\Final-course-project\app\__init__.py:72]
